### ISSUE TITLE
Make references to sprites/ lowercase.

### ISSUE THREAD

**Issue by aleksejrs** [johndbritton/mrflatland#1]
Some of them are to Sprites/, so it doesn't work on case-sensitive GNU/Linux with ext4.

**Comment by aleksejrs** [comment]
Patch: https://github.com/aleksejrs/mrflatland/commit/076e15ab9c28e3c990b93343b16f4c8ea32e43ab

**Comment by johndbritton** [comment]
I haven't looked at this code in a long time. Was this required to get the game to build?

If so, feel free to submit a pull request with the changes.

**Comment by aleksejrs** [comment]
> Was this required to get the game to build?

To run (there is no building).

**Comment by johndbritton** [comment]
Just goes to show you how long it has been since I looked at this code. :smile:

**Comment by johndbritton** [comment]
@aleksejrs I just pushed an update to the history which corrects authorship information on all the commits. You'll probably need to update your fork before you submit a pull request.
