### ISSUE TITLE
Make sure everything in the game is free

### ISSUE THREAD

**Issue by aleksejrs** [johndbritton/mrflatland#2]
To be listed in [Libregamewiki](https://libregamewiki.org) or distributed in Debian, the game must be completely free.

data/impact.ttf seems to be Monotype Impact, a font distributed by Microsoft, and is probably non-free (it is one of the "Microsoft True Type Core Fonts for the Web" for which Debian distributes an installer in contrib).

Are sounds free?  Images?

**Comment by johndbritton** [comment]
@aleksejrs Thanks for the note, somehow I ignored this repository and didn't get the notification. Are you trying to get the game listed?

**Comment by johndbritton** [comment]
Closing as stale.
